apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: testxrs.example.crossplane.io
spec:
  group: example.crossplane.io
  names:
    kind: TestXr
    plural: testxrs
  claimNames:
    kind: TestXrClaim
    plural: testxrclaims
  versions:
    - name: v1beta1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                count:
                  type: integer
                  description: "The count of resources"
              required:
                - count